### ISSUE TITLE
Thundra debugger exits without hitting the breakpoint in typescript file

### ISSUE THREAD

**Issue by s1mrankaur** [thundra-io/serverless-plugin-thundra#45]
I am using serverless-plugin-thundra and have added it in my serverless.yml file. Also added the auth key under environment and deployed the function. I also have VS Code thundra debugger added to my VSCode and need to debug my functions remotely.

When I hit the deployed function, nothing happens and all I see in the debugger is :
Thundra debugger exists without hitting the breakpoints.

My function is written in Typescript. I am not sure what to set my local root as in Thundra config as it is required to be changed. Please help figure this out.

My project structure looks like this:
```

root 
     services
          serviceA
             serverless.yml
             package.json
             src
                  handlers
                      hander.js
          serviceB
             serverless.yml
             package.json
             src
                  handlers
                      hander.js
     lib
```

**Comment by rwxdash** [comment]
Hi @s1mrankaur, thanks for reaching out. I believe you've already figured it out as we were in contact in our [Community Slack](https://www.thundra.io/thundra-slack-invitation). However, in case someone else stumbles upon this issue, I want to answer this here as well and also point our [documentation](https://apm.docs.thundra.io/node.js/online-debugging) for them as well.

About this specific question, if you want to debug your ServiceA for example in this workspace (if root is also another folder under your workspace), your local root path should be set to `./root/services/serviceA`.
