### ISSUE TITLE
How to set keepOutputDirectory to true when using serverless-bundle plugin

### ISSUE THREAD

**Issue by s1mrankaur** [thundra-io/serverless-plugin-thundra#46]
serverless-bundle plugin does not seem to have an option to override keepOutputDirectory:true. By default, it gets removed on sls deploy command.

How can we keep .webpack folder with .js and jsmap files after deployment as we need it to be able to debug remotely using thundra.

and as specified here: https://apm.docs.thundra.io/node.js/online-debugging it asks for the path where js and js and jsmap files are in case using typescript

**Comment by rwxdash** [comment]
We've also discussed this issue in our [Community Slack](https://www.thundra.io/thundra-slack-invitation), similar to #45. So, I'm going to close this issue as well.

I believe the solution was to override the option in the installed serverless-webpack package in your own node_modules folder. 

Thank you.
